version: '3.8'

services:
  stockagent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stockagent
    network_mode: "host"  # Use host network to access localhost
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - KABUSAPI_HOST=localhost
      - KABUSAPI_ENV=${KABUSAPI_ENV:-dev}
      - KABUSAPI_PASSWORD=${KABUSAPI_PASSWORD:-}
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 